/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.aruna.bookshop.views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import lk.aruna.bookshop.controller.BookController;
import lk.aruna.bookshop.model.BookDetails;

/**
 *
 * @author DELL
 */
public class Book_Details extends javax.swing.JFrame {

    DefaultTableModel dtbm;
    
    public Book_Details() {
        initComponents();
        txt_bookname.setBackground(new java.awt.Color(0, 0, 0, 1));
        loadAllBooks();
        
        jPanel1.setFocusable(true);
    }

    public Book_Details(String string, String string0, String string1, int aInt, double aDouble, String string2, int aInt0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_cancle = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        btn_Remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Book_Details = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txt_bookname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        lbl_cancle.setBackground(new java.awt.Color(0, 51, 153));
        lbl_cancle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cancle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cancle.setText("X");
        lbl_cancle.setToolTipText("Cancel");
        lbl_cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancleMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 50, 40));

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        lbl_minimize.setToolTipText("Minimize");
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        btn_Remove.setBackground(new java.awt.Color(0, 102, 153));
        btn_Remove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_Remove.setText("Edit Table");
        btn_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 140, 30));

        tbl_Book_Details.setBackground(new java.awt.Color(102, 153, 255));
        tbl_Book_Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Publisher", "Price", "Category", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Book_Details);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 840, 220));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, -1));

        txt_bookname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_bookname.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookname.setText("Book Name");
        txt_bookname.setBorder(null);
        txt_bookname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_booknameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_booknameFocusLost(evt);
            }
        });
        jPanel1.add(txt_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancleMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_cancleMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void txt_booknameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_booknameFocusGained
         if(txt_bookname.getText().trim().equals("Book Name")){
            txt_bookname.setText("");
    }
    }//GEN-LAST:event_txt_booknameFocusGained

    private void txt_booknameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_booknameFocusLost
             if(txt_bookname.getText().trim().equals("")){
            txt_bookname.setText("Book Name");
    }
    }//GEN-LAST:event_txt_booknameFocusLost

    private void btn_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseClicked
        new Edit().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_RemoveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_cancle;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JTable tbl_Book_Details;
    private javax.swing.JTextField txt_bookname;
    // End of variables declaration//GEN-END:variables

    private void loadAllBooks() {
        try {
            
            List<BookDetails> list = new BookController().getAllBooks();
            dtbm = (DefaultTableModel) tbl_Book_Details.getModel();
                 for(BookDetails OBJ:list){
                dtbm.addRow(new Object[]{
                OBJ.getBook_ID(),
                OBJ.getBook_name(),
                OBJ.getPublisher(),
                OBJ.getPrice(),
                OBJ.getCategory(),
                OBJ.getAvailability()
                
                });
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Book_Details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Book_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
  
}
