/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.aruna.bookshop.views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setColour1(){
     pnl_orders.setBackground(new Color(153,204,255));
    }
    public void setColour2(){
     pnl_corder.setBackground(new Color(153,204,255));
    }
    public void setColour3(){
     pnl_returns.setBackground(new Color(153,204,255));
    }
    public void resetColour1(){
     pnl_orders.setBackground(new Color(153,153,255));
    }
    public void resetColour2(){
     pnl_corder.setBackground(new Color(153,153,255));
    }
    public void resetColour3(){
     pnl_returns.setBackground(new Color(153,153,255));
    }
    
    
    public void settextColour1(){
    lbl_BookDetails.setForeground(new Color(51,204,255));
    }
    public void resettextColour1(){
    lbl_BookDetails.setForeground(new Color(255,255,255));
    }
     public void settextColour2(){
    lbl_OrderDetails.setForeground(new Color(51,204,255));
    }
    public void resettextColour2(){
    lbl_OrderDetails.setForeground(new Color(255,255,255));
    }
     public void settextColour3(){
    lbl_CustomOrderDetails.setForeground(new Color(51,204,255));
    }
    public void resettextColour3(){
    lbl_CustomOrderDetails.setForeground(new Color(255,255,255));
    }
     public void settextColour4(){
    lbl_returnDetails.setForeground(new Color(51,204,255));
    }
    public void resettextColour4(){
    lbl_returnDetails.setForeground(new Color(255,255,255));
    }
     public void settextColour5(){
    lbl_exit.setForeground(new Color(51,204,255));
    }
    public void resettextColour5(){
    lbl_exit.setForeground(new Color(255,255,255));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnl_corder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnl_returns = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnl_orders = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_BookDetails = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_OrderDetails = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_CustomOrderDetails = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_returnDetails = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new money.PNG"))); // NOI18N
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, 90));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.PNG"))); // NOI18N
        jLabel11.setText("jLabel10");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 90, 90));

        pnl_corder.setBackground(new java.awt.Color(153, 153, 255));
        pnl_corder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnl_corder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_corderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_corderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_corderMouseExited(evt);
            }
        });
        pnl_corder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Orders");
        pnl_corder.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Custom ");
        pnl_corder.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 30));

        jPanel1.add(pnl_corder, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 130, 120));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new return4.PNG"))); // NOI18N
        jLabel12.setText("jLabel10");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 90, 90));

        pnl_returns.setBackground(new java.awt.Color(153, 153, 255));
        pnl_returns.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnl_returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_returnsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_returnsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_returnsMouseExited(evt);
            }
        });
        pnl_returns.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Returns");
        pnl_returns.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 40));

        jPanel1.add(pnl_returns, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 130, 120));

        pnl_orders.setBackground(new java.awt.Color(153, 153, 255));
        pnl_orders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnl_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_ordersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_ordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_ordersMouseExited(evt);
            }
        });
        pnl_orders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Orders");
        pnl_orders.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 40));

        jPanel1.add(pnl_orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 130, 120));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookshop.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_BookDetails.setBackground(new java.awt.Color(102, 102, 102));
        lbl_BookDetails.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_BookDetails.setForeground(new java.awt.Color(51, 204, 255));
        lbl_BookDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_BookDetails.setText("Book Details");
        lbl_BookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BookDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BookDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BookDetailsMouseExited(evt);
            }
        });
        jPanel4.add(lbl_BookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 40));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_OrderDetails.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_OrderDetails.setForeground(new java.awt.Color(255, 255, 255));
        lbl_OrderDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_OrderDetails.setText("Order Details");
        lbl_OrderDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_OrderDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_OrderDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_OrderDetailsMouseExited(evt);
            }
        });
        jPanel5.add(lbl_OrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 40));

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_CustomOrderDetails.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_CustomOrderDetails.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CustomOrderDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CustomOrderDetails.setText("Custom Order Details");
        lbl_CustomOrderDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CustomOrderDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CustomOrderDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CustomOrderDetailsMouseExited(evt);
            }
        });
        jPanel6.add(lbl_CustomOrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 40));

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_returnDetails.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_returnDetails.setForeground(new java.awt.Color(255, 255, 255));
        lbl_returnDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_returnDetails.setText("Return Details");
        lbl_returnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_returnDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_returnDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_returnDetailsMouseExited(evt);
            }
        });
        jPanel7.add(lbl_returnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 40));

        jPanel8.setBackground(new java.awt.Color(0, 51, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_exit.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("Exit");
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });
        jPanel8.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 40));

        jLabel16.setText("jLabel16");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 530));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Dashboard");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boook image edit.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_BookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookDetailsMouseClicked
        new Book_Details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_BookDetailsMouseClicked

    private void lbl_OrderDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_OrderDetailsMouseClicked
        new Order_Deatails().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_OrderDetailsMouseClicked

    private void lbl_CustomOrderDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CustomOrderDetailsMouseClicked
        new CustomOrder_Details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_CustomOrderDetailsMouseClicked

    private void lbl_returnDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnDetailsMouseClicked
        new Return_Details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_returnDetailsMouseClicked

    private void pnl_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ordersMouseClicked
        try {
            new Order_Form().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_pnl_ordersMouseClicked

    private void pnl_corderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_corderMouseClicked
        new CustomOrder_Form().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_corderMouseClicked

    private void pnl_returnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_returnsMouseClicked
        new Return_Form().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_returnsMouseClicked

    private void pnl_ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ordersMouseEntered
        setColour1();
    }//GEN-LAST:event_pnl_ordersMouseEntered

    private void pnl_ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ordersMouseExited
        resetColour1();
    }//GEN-LAST:event_pnl_ordersMouseExited

    private void pnl_corderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_corderMouseEntered
        setColour2();
    }//GEN-LAST:event_pnl_corderMouseEntered

    private void pnl_corderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_corderMouseExited
        resetColour2();
    }//GEN-LAST:event_pnl_corderMouseExited

    private void pnl_returnsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_returnsMouseEntered
        setColour3();
    }//GEN-LAST:event_pnl_returnsMouseEntered

    private void pnl_returnsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_returnsMouseExited
        resetColour3();
    }//GEN-LAST:event_pnl_returnsMouseExited

    private void lbl_BookDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookDetailsMouseEntered
        settextColour1();
    }//GEN-LAST:event_lbl_BookDetailsMouseEntered

    private void lbl_BookDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookDetailsMouseExited
        resettextColour1();
    }//GEN-LAST:event_lbl_BookDetailsMouseExited

    private void lbl_OrderDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_OrderDetailsMouseEntered
        settextColour2();
    }//GEN-LAST:event_lbl_OrderDetailsMouseEntered

    private void lbl_OrderDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_OrderDetailsMouseExited
        resettextColour2();
    }//GEN-LAST:event_lbl_OrderDetailsMouseExited

    private void lbl_CustomOrderDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CustomOrderDetailsMouseEntered
        settextColour3();
    }//GEN-LAST:event_lbl_CustomOrderDetailsMouseEntered

    private void lbl_CustomOrderDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CustomOrderDetailsMouseExited
        resettextColour3();
    }//GEN-LAST:event_lbl_CustomOrderDetailsMouseExited

    private void lbl_returnDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnDetailsMouseEntered
        settextColour4();
    }//GEN-LAST:event_lbl_returnDetailsMouseEntered

    private void lbl_returnDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnDetailsMouseExited
        resettextColour4();
    }//GEN-LAST:event_lbl_returnDetailsMouseExited

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        settextColour5();
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        resettextColour5();
    }//GEN-LAST:event_lbl_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lbl_BookDetails;
    private javax.swing.JLabel lbl_CustomOrderDetails;
    private javax.swing.JLabel lbl_OrderDetails;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_returnDetails;
    private javax.swing.JPanel pnl_corder;
    private javax.swing.JPanel pnl_orders;
    private javax.swing.JPanel pnl_returns;
    // End of variables declaration//GEN-END:variables
}
