/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.aruna.bookshop.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lk.aruna.bookshop.controller.BookController;
import lk.aruna.bookshop.model.BookDetails;

/**
 *
 * @author DELL
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        txt_BookID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_BookName.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_Publisher.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_Price.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_Category.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_Availability.setBackground(new java.awt.Color(0, 0, 0, 1));
        
        
        
        
    }
    
    public void clear(){
        txt_BookID.setText("");
        txt_BookName.setText("");
        txt_Publisher.setText("");
        txt_Price.setText("");
        txt_Category.setText("");
        txt_Availability.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_cancle = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        txt_BookID = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_BookName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txt_Publisher = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txt_Price = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txt_Category = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txt_Availability = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_Update = new javax.swing.JButton();
        btn_Remove = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Details");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        lbl_cancle.setBackground(new java.awt.Color(0, 51, 153));
        lbl_cancle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cancle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cancle.setText("X");
        lbl_cancle.setToolTipText("Cancel");
        lbl_cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancleMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 50, 40));

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        lbl_minimize.setToolTipText("Minimize");
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 30, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        txt_BookID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_BookID.setForeground(new java.awt.Color(255, 255, 255));
        txt_BookID.setBorder(null);
        jPanel1.add(txt_BookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 270, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 270, 10));

        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Book ID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 270, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel2.setToolTipText("Search");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 30, 30));

        txt_BookName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_BookName.setForeground(new java.awt.Color(255, 255, 255));
        txt_BookName.setBorder(null);
        jPanel1.add(txt_BookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, 30));

        jLabel14.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Book Name:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 270, 10));

        txt_Publisher.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Publisher.setForeground(new java.awt.Color(255, 255, 255));
        txt_Publisher.setBorder(null);
        jPanel1.add(txt_Publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 270, 30));

        jLabel15.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Publisher:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 270, 10));

        txt_Price.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Price.setForeground(new java.awt.Color(255, 255, 255));
        txt_Price.setBorder(null);
        jPanel1.add(txt_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 270, 30));

        jLabel16.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Price:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 30));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 270, 10));

        txt_Category.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Category.setForeground(new java.awt.Color(255, 255, 255));
        txt_Category.setBorder(null);
        jPanel1.add(txt_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 270, 30));

        jLabel17.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Category:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 30));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 270, 10));

        txt_Availability.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Availability.setForeground(new java.awt.Color(255, 255, 255));
        txt_Availability.setBorder(null);
        jPanel1.add(txt_Availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 270, 30));

        jLabel18.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Availability:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 30));

        btn_Update.setBackground(new java.awt.Color(0, 102, 153));
        btn_Update.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 200, 30));

        btn_Remove.setBackground(new java.awt.Color(0, 102, 153));
        btn_Remove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_Remove.setText("Delete");
        btn_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 200, 30));

        btn_Add.setBackground(new java.awt.Color(0, 102, 153));
        btn_Add.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancleMouseClicked
        new Book_Details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_cancleMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        String id = txt_BookID.getText();
        try {
            
            BookDetails bookdetails = BookController.searchInfo(id);
            if(bookdetails!=null){
            txt_BookName.setText(bookdetails.getBook_name());
            txt_Publisher.setText(bookdetails.getPublisher());
            txt_Price.setText(bookdetails.getPrice()+"");
            txt_Category.setText(bookdetails.getCategory());
            txt_Availability.setText(bookdetails.getAvailability()+"");
            }else{
                JOptionPane.showMessageDialog(this, "Book not found");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseClicked
            BookDetails bookdetails = new BookDetails(
                    txt_BookID.getText(), 
                    txt_BookName.getText(), 
                    txt_Publisher.getText(), 
                    Double.parseDouble(txt_Price.getText()), 
                    txt_Category.getText(), 
                    Integer.parseInt(txt_Availability.getText()));
        try {
            
            boolean isUpdate = BookController.updateBookDetails(bookdetails);
             if (isUpdate) {
            JOptionPane.showMessageDialog(this, "Updated");
            }else{
            JOptionPane.showMessageDialog(this, "Try Again..");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clear();
    }//GEN-LAST:event_btn_UpdateMouseClicked

    private void btn_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseClicked
            String bookId = txt_BookID.getText().trim();
            
        try {
            boolean isDelete = BookController.DeleteBook(bookId);
            if (isDelete) {
            JOptionPane.showMessageDialog(this, "Deleted");
            }else{
            JOptionPane.showMessageDialog(this, "Try Again..");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clear();
    }//GEN-LAST:event_btn_RemoveMouseClicked

    private void btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseClicked
                String id = txt_BookID.getText();
                String name = txt_BookName.getText();
                String publisher = txt_Publisher.getText();
                double price = Double.parseDouble(txt_Price.getText());
                String category = txt_Category.getText();
                int availability = Integer.parseInt(txt_Availability.getText());
                
        try {
            
            
            boolean isSaved = new BookController().Addbook(new BookDetails(id, name, publisher, price, category, availability));
            
             if (isSaved) {
            JOptionPane.showMessageDialog(this, "Added");
            }else{
            JOptionPane.showMessageDialog(this, "Try Again..");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clear();
    }//GEN-LAST:event_btn_AddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_cancle;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JTextField txt_Availability;
    private javax.swing.JTextField txt_BookID;
    private javax.swing.JTextField txt_BookName;
    private javax.swing.JTextField txt_Category;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_Publisher;
    // End of variables declaration//GEN-END:variables
}
