/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.aruna.bookshop.views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import lk.aruna.bookshop.controller.OrderController;
import lk.aruna.bookshop.model.OrderDetails;
import lk.aruna.bookshop.model.Orders;

/**
 *
 * @author DELL
 */
public class Order_Deatails extends javax.swing.JFrame {

    /**
     * Creates new form Order_Details
     */
    DefaultTableModel dtm;
    
    public Order_Deatails() {
        initComponents();
        txt_OrderID.setBackground(new java.awt.Color(0, 0, 0, 1));
        
        jPanel1.setFocusable(true);
        
        loadAllOrders();
        calculateIncome();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_cancle = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Order_Details = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_INCOME = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_OrderID = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 20));

        lbl_cancle.setBackground(new java.awt.Color(0, 51, 153));
        lbl_cancle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cancle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cancle.setText("X");
        lbl_cancle.setToolTipText("Cancel");
        lbl_cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancleMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 40, 40));

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        lbl_minimize.setToolTipText("Minimize");
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        tbl_Order_Details.setBackground(new java.awt.Color(102, 153, 255));
        tbl_Order_Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer ID", "Date", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Order_Details);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 840, 210));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("INCOME");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 70, 40));

        txt_INCOME.setBackground(new java.awt.Color(0, 0, 102));
        txt_INCOME.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_INCOME.setForeground(new java.awt.Color(255, 255, 255));
        txt_INCOME.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_INCOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_INCOMEActionPerformed(evt);
            }
        });
        jPanel1.add(txt_INCOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 180, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, -1));

        txt_OrderID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_OrderID.setForeground(new java.awt.Color(255, 255, 255));
        txt_OrderID.setText("Order ID");
        txt_OrderID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_OrderIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_OrderIDFocusLost(evt);
            }
        });
        txt_OrderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_OrderIDKeyReleased(evt);
            }
        });
        jPanel1.add(txt_OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_INCOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_INCOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_INCOMEActionPerformed

    private void lbl_cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancleMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_cancleMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void txt_OrderIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OrderIDFocusGained
         if(txt_OrderID.getText().trim().equals("Order ID")){
            txt_OrderID.setText("");
    }
    }//GEN-LAST:event_txt_OrderIDFocusGained

    private void txt_OrderIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OrderIDFocusLost
          if(txt_OrderID.getText().trim().equals("")){
            txt_OrderID.setText("Order ID");
    }
    }//GEN-LAST:event_txt_OrderIDFocusLost

    private void txt_OrderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_OrderIDKeyReleased
        String data = txt_OrderID.getText().toLowerCase();
        filter(data);
    }//GEN-LAST:event_txt_OrderIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_Deatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_Deatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_Deatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_Deatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_Deatails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_cancle;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JTable tbl_Order_Details;
    private javax.swing.JTextField txt_INCOME;
    private javax.swing.JTextField txt_OrderID;
    // End of variables declaration//GEN-END:variables


    
     private void filter(String data){
        TableRowSorter<DefaultTableModel> tbl = new TableRowSorter<DefaultTableModel>(dtm);
        tbl_Order_Details.setRowSorter(tbl);
        
        tbl.setRowFilter(RowFilter.regexFilter(data));
    }


    private void calculateIncome() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Order_Details.getModel();

        double sum = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            sum += (double) dtm.getValueAt(i, 3);
        }

        txt_INCOME.setText(sum +"");
    }

    private void loadAllOrders() {
        try {
            
            
           List<OrderDetails> list = new OrderController().getAllOrders();
           DefaultTableModel dtm = (DefaultTableModel) tbl_Order_Details.getModel();
            for (OrderDetails OBJ : list) {
              dtm.addRow(new Object[]{
              OBJ.getOrder_ID(),
              OBJ.getCustomer_ID(),
              OBJ.getOdate(),
              OBJ.getTotal()
              
              });
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Deatails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Order_Deatails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 
    

    
}
