/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.aruna.bookshop.views;


import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.aruna.bookshop.controller.BookController;
import lk.aruna.bookshop.controller.OrderController;
import lk.aruna.bookshop.model.BookDetails;
import lk.aruna.bookshop.model.ItemDetails;
import lk.aruna.bookshop.model.Orders;

public class Order_Form extends javax.swing.JFrame {

    public Order_Form() throws ClassNotFoundException, SQLException {
        initComponents();
        txt_OrderID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_DATE.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_Qty.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_BookID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_BookName.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_CustomerID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_UnitPrice.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_Total.setBackground(new java.awt.Color(0, 0, 0, 1));
        
        
        generateOrderID();
        generateCustID();
        generateDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_cancle = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_OrderForm = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txt_OrderID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_DATE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_CustomerID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_BookID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_BookName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_Qty = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txt_UnitPrice = new javax.swing.JTextField();
        btn_Remove = new javax.swing.JButton();
        btn_PlaceOrder = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txt_Total = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        btn_Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Form");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        lbl_cancle.setBackground(new java.awt.Color(0, 51, 153));
        lbl_cancle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cancle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cancle.setText("X");
        lbl_cancle.setToolTipText("Cancel");
        lbl_cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancleMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 40));

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        lbl_minimize.setToolTipText("Minimize");
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 30, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 870, 10));

        tbl_OrderForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Qty", "Unit Price", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_OrderForm);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 870, 160));

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Order ID:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));

        txt_OrderID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_OrderID.setForeground(new java.awt.Color(255, 255, 255));
        txt_OrderID.setBorder(null);
        jPanel2.add(txt_OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calender.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 30, 30));

        txt_DATE.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_DATE.setForeground(new java.awt.Color(255, 255, 255));
        txt_DATE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_DATE.setBorder(null);
        jPanel2.add(txt_DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 130, 30));

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Customer ID:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 110, 30));

        txt_CustomerID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_CustomerID.setForeground(new java.awt.Color(255, 255, 255));
        txt_CustomerID.setBorder(null);
        jPanel2.add(txt_CustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 140, 30));

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Book ID:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        txt_BookID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_BookID.setForeground(new java.awt.Color(255, 255, 255));
        txt_BookID.setBorder(null);
        jPanel2.add(txt_BookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel2.setToolTipText("Search");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 30, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, 10));

        txt_BookName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_BookName.setForeground(new java.awt.Color(255, 255, 255));
        txt_BookName.setBorder(null);
        jPanel2.add(txt_BookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 270, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 270, 10));

        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Book Name:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 90, 30));

        jLabel14.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Qty:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        txt_Qty.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Qty.setForeground(new java.awt.Color(255, 255, 255));
        txt_Qty.setBorder(null);
        jPanel2.add(txt_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 140, 10));

        jLabel15.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Unit Price:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, 10));

        txt_UnitPrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_UnitPrice.setForeground(new java.awt.Color(255, 255, 255));
        txt_UnitPrice.setBorder(null);
        jPanel2.add(txt_UnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, 30));

        btn_Remove.setBackground(new java.awt.Color(0, 102, 153));
        btn_Remove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Remove.setText("Remove");
        btn_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseClicked(evt);
            }
        });
        jPanel2.add(btn_Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 100, 30));

        btn_PlaceOrder.setBackground(new java.awt.Color(0, 102, 153));
        btn_PlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_PlaceOrder.setText("Place Order");
        btn_PlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PlaceOrderMouseClicked(evt);
            }
        });
        jPanel2.add(btn_PlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 110, 30));

        jLabel17.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Total:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 60, 30));

        txt_Total.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Total.setForeground(new java.awt.Color(255, 255, 255));
        txt_Total.setBorder(null);
        jPanel2.add(txt_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 140, 30));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 140, 10));

        btn_Add.setBackground(new java.awt.Color(0, 102, 153));
        btn_Add.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Add.setText("Add");
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddMouseClicked(evt);
            }
        });
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancleMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_cancleMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         String id=txt_BookID.getText();
        try {
            BookDetails book = BookController.searchBook(id);
             if(book!=null){
                txt_BookName.setText(book.getBook_name());
                txt_UnitPrice.setText(Double.toString(book.getPrice()));
            }else{
                JOptionPane.showMessageDialog(this, "Book not found");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        int qty = Integer.parseInt(txt_Qty.getText());
        double unit_price =  Double.parseDouble(txt_UnitPrice.getText());
        double price = qty*unit_price;
        DefaultTableModel dtm = (DefaultTableModel) tbl_OrderForm.getModel();
        dtm.addRow(new Object[]{
            txt_BookID.getText(),
            txt_BookName.getText(),
            qty,
            unit_price,
            price
      });
        calculateSum();

        
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseClicked
        int selectedRow = tbl_OrderForm.getSelectedRow();

        if (selectedRow == -1) {
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) tbl_OrderForm.getModel();
        dtm.removeRow(selectedRow);

        calculateSum();

    }//GEN-LAST:event_btn_RemoveMouseClicked

    private void btn_PlaceOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PlaceOrderMouseClicked
            String OID = txt_OrderID.getText();
            String DATE = txt_DATE.getText();
            String CID = txt_CustomerID.getText();
            double TOTAL = Double.parseDouble(txt_Total.getText());              
            ArrayList<ItemDetails> itemDetailList = new ArrayList<>();
            DefaultTableModel dtm = (DefaultTableModel) tbl_OrderForm.getModel();
            for (int i = 0; i < dtm.getRowCount(); i++) {
            String BID = (String) dtm.getValueAt(i, 0);
            String BNAME = (String) dtm.getValueAt(i, 1);
            int QTY = (int) dtm.getValueAt(i, 2);
            double UPRICE = (double) dtm.getValueAt(i, 3);
            ItemDetails itemdetail = new ItemDetails(OID, BID, BNAME, QTY, UPRICE);
            itemDetailList.add(itemdetail);
        }
            Orders order = new Orders(OID, CID, DATE,TOTAL, itemDetailList);
            
        try {
            
            boolean isSaved = OrderController.saveOrder(order);
            if(isSaved){
                    JOptionPane.showMessageDialog(this, "Order Saved");
            }else{
                     JOptionPane.showMessageDialog(this, "Tri Again");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
               
            
            txt_Total.setText("");
            
            DefaultTableModel modal = (DefaultTableModel) tbl_OrderForm.getModel();
            
            while(modal.getRowCount()>0){
                for (int y = 0; y < modal.getRowCount(); y++) {
                    modal.removeRow(y);
                }
            }
            
        try {
            generateOrderID();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            generateCustID();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_btn_PlaceOrderMouseClicked

    private void btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseClicked
        txt_BookID.requestFocus();
        txt_BookID.setText("");
        txt_BookName.setText("");
        txt_Qty.setText("");
        txt_UnitPrice.setText("");
        
        
    }//GEN-LAST:event_btn_AddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Order_Form().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Order_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_PlaceOrder;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbl_cancle;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JTable tbl_OrderForm;
    private javax.swing.JTextField txt_BookID;
    private javax.swing.JTextField txt_BookName;
    private javax.swing.JTextField txt_CustomerID;
    private javax.swing.JTextField txt_DATE;
    private javax.swing.JTextField txt_OrderID;
    private javax.swing.JTextField txt_Qty;
    private javax.swing.JTextField txt_Total;
    private javax.swing.JTextField txt_UnitPrice;
    // End of variables declaration//GEN-END:variables

    private void generateOrderID() throws ClassNotFoundException, SQLException {
       
            String orderId = OrderController.generateOID();
            
            if(orderId !=null){
            String[] orarr = orderId.split("B");
            int ornumber = Integer.parseInt(orarr[1]);
            ornumber +=1;
            
                if(ornumber < 10){
                txt_OrderID.setText("B00"+ornumber);
                }else if(ornumber < 100){
                txt_OrderID.setText("B0"+ornumber);
                }else{
                txt_OrderID.setText("B"+ornumber);
                }

            }else{
            txt_OrderID.setText("B001");
            }
        
    }

    private void generateCustID() throws ClassNotFoundException, SQLException {
        String custId = OrderController.generateCID();
        
            if(custId !=null){
            String[] cuarr = custId.split("C");
            int cunumber = Integer.parseInt(cuarr[1]);
            cunumber +=1;
            
                if(cunumber < 10){
                txt_CustomerID.setText("C00"+cunumber);
                }else if(cunumber < 100){
                txt_CustomerID.setText("C0"+cunumber);
                }else{
                txt_CustomerID.setText("C"+cunumber);
                }

            }else{
            txt_CustomerID.setText("C001");
            }
    }

    private void generateDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txt_DATE.setText(sdf.format(date));
    }

    private void calculateSum() {
          DefaultTableModel dtm = (DefaultTableModel) tbl_OrderForm.getModel();

        double sum = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            sum += (double) dtm.getValueAt(i, 4);
        }

        txt_Total.setText(sum +"");
    }

    
}
