/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.aruna.bookshop.views;

import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
        initComponents();
         txt_RAnswer1.setBackground(new java.awt.Color(0, 0, 0, 1));
         txt_RAnswer2.setBackground(new java.awt.Color(0, 0, 0, 1));
         txt_Password.setBackground(new java.awt.Color(0, 0, 0, 1));
         txt_RPassword.setBackground(new java.awt.Color(0, 0, 0, 1));
         
        jPanel1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_minimize = new javax.swing.JLabel();
        lbl_cancle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cmb_Q1 = new javax.swing.JComboBox<>();
        txt_RAnswer1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cmb_Q2 = new javax.swing.JComboBox<>();
        txt_RAnswer2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btn_save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        txt_RPassword = new javax.swing.JTextField();
        txt_Password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        lbl_minimize.setToolTipText("Minimize");
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 40));

        lbl_cancle.setBackground(new java.awt.Color(0, 51, 153));
        lbl_cancle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cancle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cancle.setText("X");
        lbl_cancle.setToolTipText("Cancel");
        lbl_cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancleMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 40));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reset Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 330, 60));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 390, 10));

        cmb_Q1.setBackground(new java.awt.Color(0, 51, 102));
        cmb_Q1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_Q1.setForeground(new java.awt.Color(255, 255, 255));
        cmb_Q1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Security Question One", "What is your favourite colour?", "What is your favourite fruit?", "who is your favourite actor or actress?", "what is your mum's favourite singer?", "What was your favourite teacher's name?", " ", " " }));
        cmb_Q1.setToolTipText("");
        jPanel1.add(cmb_Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 410, -1));

        txt_RAnswer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_RAnswer1.setForeground(new java.awt.Color(255, 255, 255));
        txt_RAnswer1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_RAnswer1.setText("Enter your first answer");
        txt_RAnswer1.setBorder(null);
        txt_RAnswer1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RAnswer1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RAnswer1FocusLost(evt);
            }
        });
        jPanel1.add(txt_RAnswer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 410, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 410, 10));

        cmb_Q2.setBackground(new java.awt.Color(0, 51, 102));
        cmb_Q2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_Q2.setForeground(new java.awt.Color(255, 255, 255));
        cmb_Q2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Security Question Two", "What is your mum's second name?", "What was the name of your first pet?", "What was the first film you see in a theater?", "What is your favourite drink?", "What is your favourite country?", " " }));
        cmb_Q2.setToolTipText("Security Question Two");
        jPanel1.add(cmb_Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 410, -1));

        txt_RAnswer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_RAnswer2.setForeground(new java.awt.Color(255, 255, 255));
        txt_RAnswer2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_RAnswer2.setText("Enter your second answer");
        txt_RAnswer2.setBorder(null);
        txt_RAnswer2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RAnswer2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RAnswer2FocusLost(evt);
            }
        });
        jPanel1.add(txt_RAnswer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 410, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 410, 10));

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 230, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 410, 10));

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 410, 10));

        btn_save.setBackground(new java.awt.Color(0, 0, 51));
        btn_save.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("Reset");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 100, 30));

        btn_cancel.setBackground(new java.awt.Color(0, 0, 51));
        btn_cancel.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 100, 30));

        txt_RPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_RPassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_RPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_RPassword.setText("Retype your password");
        txt_RPassword.setBorder(null);
        txt_RPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txt_RPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 410, 30));

        txt_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Password.setForeground(new java.awt.Color(255, 255, 255));
        txt_Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Password.setText("Enter a password with 8 digits ");
        txt_Password.setBorder(null);
        txt_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PasswordFocusLost(evt);
            }
        });
        jPanel1.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 410, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blur.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
            new Login().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
            new Login().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void lbl_cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancleMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_cancleMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void txt_RAnswer1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RAnswer1FocusGained
          if(txt_RAnswer1.getText().trim().equals("Enter your first answer")){
            txt_RAnswer1.setText("");
    }
    }//GEN-LAST:event_txt_RAnswer1FocusGained

    private void txt_RAnswer1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RAnswer1FocusLost
         if(txt_RAnswer1.getText().trim().equals("")){
            txt_RAnswer1.setText("Enter your first answer");
    }
    }//GEN-LAST:event_txt_RAnswer1FocusLost

    private void txt_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PasswordFocusGained
         if(txt_Password.getText().trim().equals("Enter a password with 8 digits")){
            txt_Password.setText("");
    }
    }//GEN-LAST:event_txt_PasswordFocusGained

    private void txt_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PasswordFocusLost
         if(txt_Password.getText().trim().equals("")){
            txt_Password.setText("Enter a password with 8 digits");
    }
    }//GEN-LAST:event_txt_PasswordFocusLost

    private void txt_RPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPasswordFocusGained
         if(txt_RPassword.getText().trim().equals("Retype your password")){
            txt_RPassword.setText("");
    }
    }//GEN-LAST:event_txt_RPasswordFocusGained

    private void txt_RPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPasswordFocusLost
         if(txt_RPassword.getText().trim().equals("")){
            txt_RPassword.setText("Retype your password");
    }
    }//GEN-LAST:event_txt_RPasswordFocusLost

    private void txt_RAnswer2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RAnswer2FocusGained
         if(txt_RAnswer2.getText().trim().equals("Enter your second answer")){
            txt_RAnswer2.setText("");
    }
    }//GEN-LAST:event_txt_RAnswer2FocusGained

    private void txt_RAnswer2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RAnswer2FocusLost
         if(txt_RAnswer2.getText().trim().equals("")){
            txt_RAnswer2.setText("Enter your second answer");
    }
    }//GEN-LAST:event_txt_RAnswer2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_Q1;
    private javax.swing.JComboBox<String> cmb_Q2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_cancle;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_RAnswer1;
    private javax.swing.JTextField txt_RAnswer2;
    private javax.swing.JTextField txt_RPassword;
    // End of variables declaration//GEN-END:variables
}
