/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.aruna.bookshop.views;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.aruna.bookshop.controller.OrderController;
import lk.aruna.bookshop.controller.ReturnController;
import lk.aruna.bookshop.model.ItemDetails;
import lk.aruna.bookshop.model.Orders;
import lk.aruna.bookshop.model.ReturnDetails;

/**
 *
 * @author DELL
 */
public class Return_Form extends javax.swing.JFrame {

    /**
     * Creates new form Return_Form
     */
    public Return_Form() {
        initComponents();
        txt_OrderID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_DATE.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_BookID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_BookName.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_CustomerID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_OrderDate.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_TotalBill.setBackground(new java.awt.Color(0, 0, 0, 1));
        
        generateDate();
        jPanel1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_cancle = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        btn_return = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ReturnForm = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_OrderID = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txt_DATE = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txt_CustomerID = new javax.swing.JTextField();
        txt_BookID = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_BookName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_OrderDate = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txt_TotalBill = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return Form");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        lbl_cancle.setBackground(new java.awt.Color(0, 51, 153));
        lbl_cancle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cancle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cancle.setText("X");
        lbl_cancle.setToolTipText("Cancel");
        lbl_cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancleMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 50, 40));

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        lbl_minimize.setToolTipText("Minimize");
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        btn_return.setBackground(new java.awt.Color(0, 102, 153));
        btn_return.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_return.setText("RETURN");
        btn_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_returnMouseClicked(evt);
            }
        });
        jPanel1.add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 830, 10));

        tbl_ReturnForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Book ID", "Book Name", "Qty", "Unit Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_ReturnForm);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 160));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("R.Book ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 30));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("R.Book Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 30));

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Customer ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 110, 30));

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Order ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));

        txt_OrderID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_OrderID.setForeground(new java.awt.Color(255, 255, 255));
        txt_OrderID.setText(" Order ID");
        txt_OrderID.setBorder(null);
        txt_OrderID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_OrderIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_OrderIDFocusLost(evt);
            }
        });
        jPanel1.add(txt_OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 10));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calender.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 30, 30));

        txt_DATE.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_DATE.setForeground(new java.awt.Color(255, 255, 255));
        txt_DATE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_DATE.setBorder(null);
        jPanel1.add(txt_DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 130, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 160, 10));

        txt_CustomerID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_CustomerID.setForeground(new java.awt.Color(255, 255, 255));
        txt_CustomerID.setBorder(null);
        jPanel1.add(txt_CustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 160, 30));

        txt_BookID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_BookID.setForeground(new java.awt.Color(255, 255, 255));
        txt_BookID.setBorder(null);
        jPanel1.add(txt_BookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 160, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 160, 10));

        txt_BookName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_BookName.setForeground(new java.awt.Color(255, 255, 255));
        txt_BookName.setBorder(null);
        jPanel1.add(txt_BookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 330, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 330, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel2.setToolTipText("Search");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 30, 30));

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Order date:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 110, 30));

        txt_OrderDate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_OrderDate.setForeground(new java.awt.Color(255, 255, 255));
        txt_OrderDate.setBorder(null);
        jPanel1.add(txt_OrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 160, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 160, 10));

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Total bill:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 110, 30));

        txt_TotalBill.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_TotalBill.setForeground(new java.awt.Color(255, 255, 255));
        txt_TotalBill.setBorder(null);
        jPanel1.add(txt_TotalBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 160, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 160, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancleMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_cancleMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void txt_OrderIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OrderIDFocusGained
         if(txt_OrderID.getText().trim().equals("Order ID")){
            txt_OrderID.setText("");
    }
    }//GEN-LAST:event_txt_OrderIDFocusGained

    private void txt_OrderIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OrderIDFocusLost
            if(txt_OrderID.getText().trim().equals("")){
            txt_OrderID.setText("Order ID");
    }
    }//GEN-LAST:event_txt_OrderIDFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String oid = txt_OrderID.getText();
        try {
            
            List<ItemDetails> list = new OrderController().searchOrders(oid);
            DefaultTableModel dtbm = (DefaultTableModel) tbl_ReturnForm.getModel();
            for (ItemDetails OBJ : list) {
            dtbm.addRow(new Object[]{
            OBJ.getOrder_ID(),
            OBJ.getBook_ID(),
            OBJ.getBook_name(),
            OBJ.getQty(),
            OBJ.getUnit_price()
            });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Return_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Return_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        try {
            
            Orders order = OrderController.getDetails(oid);
            if(order!=null){
                txt_CustomerID.setText(order.getCustomer_ID());
                txt_OrderDate.setText(order.getOdate());
                txt_TotalBill.setText(order.getTotal()+"");
            }else{
                JOptionPane.showMessageDialog(this, "Order not found");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Return_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Return_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnMouseClicked
        ReturnDetails r1 = new ReturnDetails(
                txt_OrderID.getText(), 
                txt_CustomerID.getText(), 
                txt_DATE.getText(), 
                txt_BookID.getText(), 
                txt_BookName.getText());
        
        try {
            
            boolean isSaved = ReturnController.saveReturns(r1);
            if(isSaved){
                JOptionPane.showMessageDialog(this, "Saved");
            }else{
                JOptionPane.showMessageDialog(this, "Try again");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Return_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txt_OrderID.setText("");
        txt_CustomerID.setText("");
        txt_BookID.setText("");
        txt_BookName.setText("");
        txt_OrderDate.setText("");
        txt_TotalBill.setText("");
        
         DefaultTableModel modal = (DefaultTableModel) tbl_ReturnForm.getModel();
            
            while(modal.getRowCount()>0){
                for (int i = 0; i < modal.getRowCount(); i++) {
                    modal.removeRow(i);
                }
            }
        
    }//GEN-LAST:event_btn_returnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbl_cancle;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JTable tbl_ReturnForm;
    private javax.swing.JTextField txt_BookID;
    private javax.swing.JTextField txt_BookName;
    private javax.swing.JTextField txt_CustomerID;
    private javax.swing.JTextField txt_DATE;
    private javax.swing.JTextField txt_OrderDate;
    private javax.swing.JTextField txt_OrderID;
    private javax.swing.JTextField txt_TotalBill;
    // End of variables declaration//GEN-END:variables

    private void generateDate() {
         Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txt_DATE.setText(sdf.format(date));
    }
}
